[[main]]
none = "none"

[[main]]
name = "Noticias"
pageRef = "novas"
weight = 1

[[main]]
name = "Proyectos"
weight = 2

[[main]]
name = "Sementeira"
parent = "Proyectos"
url = "https://sementeira.maega.gal/"
weight = 2

[[main]]
name = "MáisMates"
parent = "Proyectos"
url = "https://www.usc.gal/gl/centro/facultade-matematicas/revista-estudiantil-mates"
weight = 2

[[main]]
name = "Aurias"
parent = "Proyectos"
pageRef = "proxectos/aurias"
weight = 2

[[main]]
name = "Charlas"
parent = "Proyectos"
pageRef = "proxectos/charlas institutos/formulario"
weight = 2

[[main]]
name = "Herramientas"
weight = 3

[[main]]
name = "Configurador de Horarios de Mates-USC"
parent = "Herramientas"
url = "https://forms.gle/TPJx94Dg6L1fUVgeA"
weight = 3

[[subnavigation]]
name = "Únete!"
url = "https://forms.gle/yVniZyvwQZB13z7B7"
weight = 10

[[main]]
pre = "x-twitter"
url = "https://x.com/maega_gal"
identifier = "SIbcHt624n"
weight = 4

[[main]]
pre = "instagram"
url = "https://instagram.com/maega.gal"
identifier = "oOO8cS6UJ1"
weight = 5

[[footer]]
name = "Contacto"
url = "mailto:asociacion@maega.gal"

[[footer]]
name = "Etiquetas"
pageRef = "tags"
weight = 10

[[footer]]
name = "Fuentes"
pageRef = "authors"
weight = 11